In [28]:
import numpy as np

In [29]:
import pandas as pd
#import library numpy dan pandas

In [30]:
df=pd.read_csv('emositwiter.csv',sep=',')
#read csv file

In [31]:
df.head()
#verifikasi 5 row data pertama saja

label                                              tweet
0  anger  Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...
1  anger  Sesama cewe lho (kayaknya), harusnya bisa lebi...
2  happy  Kepingin gudeg mbarek Bu hj. Amad Foto dari go...
3  anger  Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...
4  happy  Sharing pengalaman aja, kemarin jam 18.00 bata...

In [32]:
df.tail()
#verifikasi 5 row data terakhir saja

label                                              tweet
4396     love  Tahukah kamu, bahwa saat itu papa memejamkan m...
4397     fear  Sulitnya menetapkan Calon Wapresnya Jokowi di ...
4398    anger  5. masa depannya nggak jelas. lha iya, gimana ...
4399    happy  [USERNAME] dulu beneran ada mahasiswa Teknik U...
4400  sadness  Ya Allah, hanya Engkau yang mengetahui rasa sa...

In [33]:
df.columns
#verifikasi nama kolom

Index(['label', 'tweet'], dtype='object')

In [34]:
df.isnull().sum()
#verifikasi kelengkapan data

label    0
tweet    0
dtype: int64

In [35]:
len(df)
#verdifikasi panjang row data

4401

In [36]:
df['label'].value_counts()
#melihat unik value dari kolom label nya

anger      1101
happy      1017
sadness     997
fear        649
love        637
Name: label, dtype: int64

In [55]:
import sklearn
from sklearn.model_selection import train_test_split

In [56]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
def remove_punctuation(text):
    import string
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

df['tweet'] = df['tweet'].apply(remove_punctuation)

factory = StopWordRemoverFactory()
sw = factory.get_stop_words()
def stopwords(text):
    text = [word.lower() for word in text.split() if word.lower() not in sw]
    return " ".join(text)
df['tweet'] = df['tweet'].apply(stopwords)

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(text):    
    text = [stemmer.stem(word) for word in text.split()]
    return " ".join(text)

df['tweet'] = df['tweet'].apply(stemming)


In [57]:
X = df['tweet']
#isi tweets

In [58]:
y = df['label']
#label 'keluhan', 'respon' dan 'bukan keluhan atau respon'

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state=42)
#test data 30%, traing data 70%

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [61]:
from sklearn.linear_model import LogisticRegression
#Menggunakan algoritma Logistic Regresion

In [62]:
from sklearn.pipeline import Pipeline
#Pipeline kelas perform kombinasi semua nya tfidf vectorizer dan model yg dipakai

In [63]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',LogisticRegression()
)])
#semua step dalam satu single step

In [64]:
text_clf.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling

In [65]:
predictions = text_clf.predict(X_test)

In [66]:
from sklearn.metrics import confusion_matrix,classification_report

In [67]:
print(confusion_matrix(y_test,predictions))

[[268   9  25   2  46]
 [ 26 111  17   4  23]
 [ 51   1 209   6  40]
 [  6   3  20 136  26]
 [ 65   6  48  17 156]]


In [68]:
print(classification_report(y_test,predictions))
#statistik hasil test dari training data

              precision    recall  f1-score   support

       anger       0.64      0.77      0.70       350
        fear       0.85      0.61      0.71       181
       happy       0.66      0.68      0.67       307
        love       0.82      0.71      0.76       191
     sadness       0.54      0.53      0.54       292

    accuracy                           0.67      1321
   macro avg       0.70      0.66      0.68      1321
weighted avg       0.68      0.67      0.67      1321



In [69]:
from sklearn import metrics

In [70]:
metrics.accuracy_score(y_test,predictions)
#akurasi untuk 30% data test

0.6661619984859954

In [71]:
text_clf.predict(["RT @infobdg: #suaraBDG via @aldlansyah: Tombol sama lampu penyebrangannya engga berfungsi nih, pak cc: @dishub_kotabdg https://t.co/NvtS3Eq…"])
#paste syntax disini untuk di uji - belum pakai GUI

array(['anger'], dtype=object)